# -*- coding: utf-8 -*-
"""serial killer 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDl36PPe1jdxfC9edVyENnpKAF93k5ky
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


# Load the CSV files into separate DataFrames
d1 = pd.read_csv('5_to_14_victim_count.csv')
d2 = pd.read_csv('15_to_30_victim_count.csv')
d3 = pd.read_csv('Highest_victim_count.csv')
d4 = pd.read_csv('Lessthan_5_victim_count.csv')

# Concatenate the DataFrames into a single DataFrame
all_data = pd.concat([d1, d2, d3, d4], ignore_index=True)
all_data.info()
all_data .shape
all_data .head()

all_data.isna().sum()
all_data.loc[all_data['Possible victims'].isna(),'Possible victims']=all_data['Proven victims']
all_data=all_data.fillna(value=all_data['Proven victims'])
all_data.isna().sum()

all_data['Country'].value_counts().head(10).plot.bar(facecolor='r',edgecolor ='g')
plt.style.use('ggplot')

s=all_data['Years active'].str.split(pat=" ",n=1,expand=True)
all_data['Start year']=s[0]
all_data.head()

s=all_data['Country'].str.split(pat="\r",n=1,expand=True)
all_data['Country']=s[0]
all_data.head()

all_data.sample(10)